### ISSUE TITLE
Auto switch not working after installing version

### ISSUE THREAD

**Issue by cmacsithigh** [marcdomain/tfv#10]
There seems to be an issue with using auto switch once you have the specific version installed.

**Device Information**
OS: Windows
Version: 3.2.4

**Example 1**

Project A has a requirement for version 1.3.0 but you don't have it installed. If you run `tfv as` it works perfectly.

**Example 2**
Project B has a requirement for version 1.3.9 which you already have installed. If you run `tfv as` you get an error (see screenshot)
![image](https://user-images.githubusercontent.com/30445066/223704570-c96a5bc3-7b6b-4736-b0d2-d61e5893a7ad.png)

**Problem**
From doing a bit of digging there seems to be an issue when you're passing the version into the [`use` module](https://github.com/marcdomain/tfv/blob/cacdbfa170bf3bbf2f7c7fe38dc6e9f83614cd52/lib/modules/switch.js#L46.). It passes `version.exe` and then will add an additional `.exe` [here](https://github.com/marcdomain/tfv/blob/cacdbfa170bf3bbf2f7c7fe38dc6e9f83614cd52/lib/modules/use.js#L15) if the OS is windows

If you need any more information please let me know.

**Comment by marcdomain** [comment]
Thanks for the feedback. It will be fixed shortly.

**Comment by marcdomain** [comment]
It's done. Thanks and enjoy 🎉

**Comment by cmacsithigh** [comment]
Awesome. Thanks @marcdomain. Really enjoying how easy this tool is to use so far.

**Comment by marcdomain** [comment]
Thanks for the compliment @cian-sheehy. The goal is to make life easy 🙂
If you use VS code, you can try this extension https://marketplace.visualstudio.com/items?itemName=marcdomain.ignoreit

**Comment by marcdomain** [comment]
https://github.com/marcdomain/ignoreit
