### ISSUE TITLE
Can't run terraform after installing the tfv install <terraform version>

### ISSUE THREAD

**Issue by kelvinotuya** [marcdomain/tfv#18]
Hello, very great idea for this package. I was able to install this package easily but when I try to run the terraform version afterwards, it says "'terraform' is not recognized as an internal or external command". Am I missing something? Thanks

**Comment by marcdomain** [comment]
Hello Kelvin. Thanks for the compliment.
- Did you run `tfv use <VERSION>` after the installation? 
- What are the commands you ran?

**Comment by marcdomain** [comment]
This issue is closed as there has been no response after 2 weeks.
